### ISSUE TITLE
在ABP里的循环语句中使用分表查询报错

### ISSUE THREAD

**Issue by TangJun815** [xuejmnet/sharding-core#91]
分表属性是：Code

foreach (var item in dtos)
{
    var queryableK1Day = await k1DaysRepository.GetQueryableAsync();
    K_1Day attentionEntity = queryableK1Day
                        .Where(a => a.Code == item.Code && a.TradeDate <= item.AttentionDate)
                        .OrderByDescending(a => a.TradeDate)
                        .LastOrDefault();
    if (attentionEntity != null)
    {
        item.PriceAttentionDate = attentionEntity.ClosePrice;
    }

}

[09:50:24 ERR] Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> ShardingCore.Exceptions.ShardingCoreTableQueryRouteNotMatchException: DbSet<K_1Day>()
    .OrderByDescending(a => a.TradeDate)
    .LastOrDefault(a => a.Code == <>c__DisplayClass24_2.CS$<>8__locals1.item.Code)
   at ShardingCore.Sharding.StreamMergeContext`1.PreperExecute[TResult](Func`1 emptyFunc)
   at ShardingCore.Sharding.MergeEngines.Abstractions.InMemoryMerge.AbstractInMemoryAsyncMergeEngine`1.ExecuteAsync[TResult](Func`2 efQuery, CancellationToken cancellationToken)
   at ShardingCore.Sharding.StreamMergeEngines.LastOrDefaultAsyncInMemoryMergeEngine`1.DoMergeResultAsync(CancellationToken cancellationToken)
   at ShardingCore.Sharding.MergeEngines.Abstractions.InMemoryMerge.AbstractTrackEnsureMethodCallWhereInMemoryAsyncMergeEngine`1.MergeResultAsync(CancellationToken cancellationToken)
   at ShardingCore.Extensions.TaskExtension.WaitAndUnwrapException[TResult](Task`1 task, Boolean continueOnCapturedContext)
   at ShardingCore.Sharding.MergeEngines.Abstractions.InMemoryMerge.AbstractEnsureMethodCallInMemoryAsyncMergeEngine`2.MergeResult()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at ShardingCore.Sharding.ShardingQueryExecutors.DefaultShardingQueryExecutor.EnsureResultTypeMergeExecute[TResult](Type streamMergeEngineType, IMergeQueryCompilerContext mergeQueryCompilerContext, Boolean async, CancellationToken cancellationToken)
   at ShardingCore.Sharding.ShardingQueryExecutors.DefaultShardingQueryExecutor.DoExecute[TResult](IMergeQueryCompilerContext mergeQueryCompilerContext, Boolean async, CancellationToken cancellationToken)
   at ShardingCore.Sharding.ShardingQueryExecutors.DefaultShardingQueryExecutor.Execute[TResult](IMergeQueryCompilerContext mergeQueryCompilerContext)
   at ShardingCore.Sharding.ShardingExecutors.DefaultShardingTrackQueryExecutor.Execute[TResult](IQueryCompilerContext queryCompilerContext)
   at ShardingCore.Sharding.ShardingExecutors.DefaultShardingComplierExecutor.Execute[TResult](IShardingDbContext shardingDbContext, Expression query)
   at ShardingCore.EFCores.ShardingQueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.LastOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)

**Comment by xuejmnet** [comment]
@TangJun815 您好很高兴您关注本框架，您可以看下item.code是否存在于shardingcore中

```c#

var virtualTableManager = ShardingContainer.GetService<IVirtualTableManager<DefaultShardingDbContext>>();
            var virtualTable = virtualTableManager.GetVirtualTable<SysUserMod>();
            var virtualTableRoute = virtualTable.GetVirtualRoute();
            var allTails = virtualTableRoute.GetAllTails();

```

**Comment by TangJun815** [comment]
的确是自己在实现虚拟路由表的重载方法时出的错。
修订了自己实现类的如下方法就对了：
`public override List<string> GetAllTails()
  {
 }`
